/*
 * Copyright (c) 2006-2013 Rogério Liesenfeld
 * This file is subject to the terms of the MIT license (see LICENSE.txt).
 */
package powermock.examples.mockpolicy.policy;

import mockit.*;
import powermock.examples.mockpolicy.nontest.*;
import powermock.examples.mockpolicy.nontest.domain.*;

/**
 * A mock class that intercepts calls to {@link Dependency#getData()} and returns a substitute value.
 */
public final class MyCustomMockClass extends MockUp<Dependency>
{
   @Mock
   public DataObject getData()
   {
      return new DataObject("Data object generated by mock class");
   }
}
