/*
 * Copyright (c) 2006-2014 Rogério Liesenfeld
 * This file is subject to the terms of the MIT license (see LICENSE.txt).
 */
package powermock.examples.mockpolicy;

import org.junit.*;

import static org.junit.Assert.*;
import powermock.examples.mockpolicy.nontest.domain.*;
import powermock.examples.mockpolicy.policy.*;

/**
 * <a href="http://code.google.com/p/powermock/source/browse/trunk/examples/DocumentationExamples/src/test/java/powermock/examples/mockpolicy/DependencyUserTest.java">PowerMock version</a>
 */
public final class DependencyUser_JMockit_Test
{
   @BeforeClass
   public static void setUp()
   {
      new MyCustomMockClass();
   }

   @Test
   public void assertThatMyFirstMockClassWork()
   {
      DataObject dependencyData = new DependencyUser().getDependencyData();
      assertEquals("Data object generated by mock class", dependencyData.getData());
   }
}
